# Header
menu:
  首页: /
  归档: /archives
  # 标签: /tags
  # 分类: /categories
  小抄: /quick-notes
  关于: /about

# RSS订阅需要安装：npm install hexo-generator-feed --save
rss: /atom.xml
nav: right
mobile_nav: right



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts
- blogroll

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
# background_image: /images/bg.jpg
# background_title: 空城盼故人

# favicon
favicon: https://q1.qlogo.cn/g?b=qq&nk=979727728&s=640

#Userinfo
author: 许嵩老公
slogan: 深吸一口梦，吹个气球存起来。
avatar: https://q1.qlogo.cn/g?b=qq&nk=979727728&s=640
avatar_title: 图片来自QQ

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  owner: 
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: NOVpqBhVVjZHOamocUf3Grijt7xAK_Engoe_FNrxE3Q
baidu_site_verification: HBrapLOndy

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 友情链接
blogroll:
  Github Pages: https://xiaoyan94.github.io/
  Gitee Pages: https://xy94.gitee.io/
