# This is a basic workflow to help you get started with Actions

name: Deploy Blog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!

    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
        
    - name: Use Node.js 10.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "10.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.PRIVATE_KEY_FOR_GITHUB_AND_GITEE }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'xiaoyan94' # 换成你自己的邮箱和名字
        git config --global user.email 'ruguo_0904@163.com'
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
        npm install hexo-generator-feed --save
        npm install hexo-generator-baidu-sitemap@0.1.6 --save
        npm install https://github.com/CodeFalling/hexo-asset-image --save
        echo "安装hexo-asset-image,配合vscode-paste-image使用"
  
    - name: Hexo Deploy
      env:
        REPOSITORY_HOME: ${{github.workspace}}
      run: |
        # publish
        # hexo generate && hexo deploy # 执行部署程序
        hexo g
        echo "gōng zuò mù lù：$REPOSITORY_HOME"
        cd $REPOSITORY_HOME
        chmod +x replace_url_baidusitemap.sh
        bash ./replace_url_baidusitemap.sh
        hexo d

    - name: Setup Chrome,selenium env
      env:
        REPOSITORY_HOME: ${{github.workspace}}
      run: |
        # cd $REPOSITORY_HOME
        # Install Google Chrome
        # https://askubuntu.com/questions/79280/how-to-install-chrome-browser-properly-via-command-line
        # sudo apt-get install libxss1 libappindicator1 libindicator7
        # wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        # sudo dpkg -i google-chrome*.deb  # Might show "errors", fixed by next line
        # sudo apt-get install -f
        # wget http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
        # unzip chromedriver_linux64.zip
        # pip3 install selenium
        echo "此步骤已经转移至远程服务器上的脚本执行,通过下面的SSH连接至远程服务器。"

    - name: Auto update Gitee Pages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        # password: ${{ secrets.SSH_PASSWORD }} 
        key: ${{ secrets.DEPLOY_BANWAGON_PRIV_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # whoami
          # ls -al
          python3 update_gitee.py
